// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVxFw8lYU7twtbxwqscnI6Gqq-ryPZ7lo',
    appId: '1:936523733133:web:1c011ec75122e54bc3eac4',
    messagingSenderId: '936523733133',
    projectId: 'devsnippet-app',
    authDomain: 'devsnippet-app.firebaseapp.com',
    storageBucket: 'devsnippet-app.firebasestorage.app',
    measurementId: 'G-4WMG4Z3STG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-cXk9cU8sWvXfaWYFOfMR4Wh8tQ9KcCc',
    appId: '1:936523733133:android:17708e4d5620937cc3eac4',
    messagingSenderId: '936523733133',
    projectId: 'devsnippet-app',
    storageBucket: 'devsnippet-app.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBegi1-i6neI3Ht2bcWAsL7kGNT1HdvFsk',
    appId: '1:936523733133:ios:181cc5657a447078c3eac4',
    messagingSenderId: '936523733133',
    projectId: 'devsnippet-app',
    storageBucket: 'devsnippet-app.firebasestorage.app',
    iosClientId: '936523733133-95m98c6f9fj1h1ta04soar4kba8n3g77.apps.googleusercontent.com',
    iosBundleId: 'com.example.devsnippet1',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBegi1-i6neI3Ht2bcWAsL7kGNT1HdvFsk',
    appId: '1:936523733133:ios:181cc5657a447078c3eac4',
    messagingSenderId: '936523733133',
    projectId: 'devsnippet-app',
    storageBucket: 'devsnippet-app.firebasestorage.app',
    iosClientId: '936523733133-95m98c6f9fj1h1ta04soar4kba8n3g77.apps.googleusercontent.com',
    iosBundleId: 'com.example.devsnippet1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVxFw8lYU7twtbxwqscnI6Gqq-ryPZ7lo',
    appId: '1:936523733133:web:c418813272a2d2c0c3eac4',
    messagingSenderId: '936523733133',
    projectId: 'devsnippet-app',
    authDomain: 'devsnippet-app.firebaseapp.com',
    storageBucket: 'devsnippet-app.firebasestorage.app',
    measurementId: 'G-5JW4QR1Y6B',
  );
}
